version: "3.3"

services:

  nginx-proxy:
    build: nginx
    restart: always
    networks:
      - no-internet
      - default
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=flask-app:8000
    ports:
      - '42424:443'
      - '42425:42425'
    depends_on:
      - flask-app
      - pypiserver-authenticated
    command: /app/start.sh

  flask-app:
    build: flask
    restart: always
    networks:
      - no-internet
    depends_on:
      - pypiserver-authenticated
    command: supervisord

  pypiserver-authenticated:
    image: pypiserver/pypiserver:latest
    networks:
      - no-internet
    volumes:
      - ./auth/htpasswd:/data/htpasswd
      - ./packages/concrete_calculator-1.9.9.9.9.9.9.9.9.9-py2.py3-none-any.whl:/data/packages/concrete_calculator-1.9.9.9.9.9.9.9.9.9-py2.py3-none-any.whl
      - ./pypi/_app.py:/usr/local/lib/python3.8/site-packages/pypiserver/_app.py
      - ./pypi/welcome.html:/usr/local/lib/python3.8/site-packages/pypiserver/welcome.html
      - ./pypi/check:/data/check
    command: run --disable-fallback -P /data/htpasswd -p 42425 --hash-algo sha256 -a update,download,list /data/packages

networks:
  no-internet:
    driver: bridge
    internal: true

  default:
    external:
      name: "clownconcrete_default"

